api_controllers:
    resource:
        path: '../src/UI/Http/Rest/Controller/'
        namespace: App\UI\Http\Rest\Controller
    type: attribute
    prefix: /api

web_controllers:
    resource:
        path: '../src/UI/Http/Web/Controller/'
        namespace: App\UI\Http\Web\Controller
    type: attribute
